"""add is_active to saved_cities

Revision ID: 0d514e57de6b
Revises: 5e652d523afd
Create Date: 2026-08-15 21:53:15.109522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d514e57de6b'
down_revision: Union[str, Sequence[str], None] = '5e652d523afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('saved_cities', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_cities', 'is_active')
    # ### end Alembic commands ###
